name: SSH Deploy

on:
  push:
    branches:
      - main

jobs:
  remote-command:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run remote command via SSH
      uses: appleboy/ssh-action@v1.1.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: ${{ secrets.PORT }}
        script: |
          docker exec -i -w /usr/local/apache2/htdocs apache bash -c 'git pull'
